/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/~__root'
import { Route as LayoutRouteImport } from './routes/~_layout'
import { Route as LayoutIndexRouteImport } from './routes/~_layout/~index'
import { Route as LayoutAuthSignupRouteImport } from './routes/~_layout/~_auth/~signup'
import { Route as LayoutAuthLoginRouteImport } from './routes/~_layout/~_auth/~login'
import { Route as LayoutProfileUserIdIndexRouteImport } from './routes/~_layout/~profile.$userId/~index'
import { Route as LayoutForumTypeIndexRouteImport } from './routes/~_layout/~forum/~$type/~index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthSignupRoute = LayoutAuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthLoginRoute = LayoutAuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileUserIdIndexRoute =
  LayoutProfileUserIdIndexRouteImport.update({
    id: '/profile/$userId/',
    path: '/profile/$userId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutForumTypeIndexRoute = LayoutForumTypeIndexRouteImport.update({
  id: '/forum/$type/',
  path: '/forum/$type/',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LayoutAuthLoginRoute
  '/signup': typeof LayoutAuthSignupRoute
  '/forum/$type': typeof LayoutForumTypeIndexRoute
  '/profile/$userId': typeof LayoutProfileUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/login': typeof LayoutAuthLoginRoute
  '/signup': typeof LayoutAuthSignupRoute
  '/forum/$type': typeof LayoutForumTypeIndexRoute
  '/profile/$userId': typeof LayoutProfileUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_auth/login': typeof LayoutAuthLoginRoute
  '/_layout/_auth/signup': typeof LayoutAuthSignupRoute
  '/_layout/forum/$type/': typeof LayoutForumTypeIndexRoute
  '/_layout/profile/$userId/': typeof LayoutProfileUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/forum/$type' | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/forum/$type' | '/profile/$userId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/_auth/login'
    | '/_layout/_auth/signup'
    | '/_layout/forum/$type/'
    | '/_layout/profile/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_auth/signup': {
      id: '/_layout/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LayoutAuthSignupRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_auth/login': {
      id: '/_layout/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutAuthLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/$userId/': {
      id: '/_layout/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof LayoutProfileUserIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/forum/$type/': {
      id: '/_layout/forum/$type/'
      path: '/forum/$type'
      fullPath: '/forum/$type'
      preLoaderRoute: typeof LayoutForumTypeIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAuthLoginRoute: typeof LayoutAuthLoginRoute
  LayoutAuthSignupRoute: typeof LayoutAuthSignupRoute
  LayoutForumTypeIndexRoute: typeof LayoutForumTypeIndexRoute
  LayoutProfileUserIdIndexRoute: typeof LayoutProfileUserIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAuthLoginRoute: LayoutAuthLoginRoute,
  LayoutAuthSignupRoute: LayoutAuthSignupRoute,
  LayoutForumTypeIndexRoute: LayoutForumTypeIndexRoute,
  LayoutProfileUserIdIndexRoute: LayoutProfileUserIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
